version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
  elasticsearch:
    image: elasticsearch:7.14.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node